DROP TABLE IF EXISTS `service_booking_bookings`;
CREATE TABLE IF NOT EXISTS `service_booking_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `calendar_id` int(10) unsigned DEFAULT NULL,
  `booking_total` decimal(9,2) unsigned DEFAULT NULL,
  `booking_deposit` decimal(9,2) unsigned DEFAULT NULL,
  `booking_tax` decimal(9,2) unsigned DEFAULT NULL,
  `booking_status` enum('pending','confirmed','cancelled') DEFAULT NULL,
  `payment_method` enum('paypal','authorize','creditcard') DEFAULT NULL,
  `payment_option` enum('deposit','total') DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `customer_email` varchar(255) DEFAULT NULL,
  `customer_phone` varchar(255) DEFAULT NULL,
  `customer_country` int(10) unsigned DEFAULT NULL,
  `customer_city` varchar(255) DEFAULT NULL,
  `customer_state` varchar(255) DEFAULT NULL,
  `customer_zip` varchar(255) DEFAULT NULL,
  `customer_address` varchar(255) DEFAULT NULL,
  `customer_notes` text,
  `cc_type` varchar(255) DEFAULT NULL,
  `cc_num` varchar(255) DEFAULT NULL,
  `cc_exp` varchar(255) DEFAULT NULL,
  `cc_code` varchar(255) DEFAULT NULL,
  `txn_id` varchar(255) DEFAULT NULL,
  `processed_on` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `calendar_id` (`calendar_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_bookings_details`;
CREATE TABLE IF NOT EXISTS `service_booking_bookings_details` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned DEFAULT NULL,
  `service_id` int(10) unsigned DEFAULT NULL,
  `employee_id` int(10) unsigned DEFAULT NULL,
  `date` date DEFAULT NULL,
  `start` time DEFAULT NULL,
  `start_ts` int(10) unsigned DEFAULT NULL,
  `total` smallint(5) unsigned DEFAULT NULL,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  `reminder_email` tinyint(1) unsigned DEFAULT '0',
  `reminder_sms` tinyint(1) unsigned DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_calendars`;
CREATE TABLE IF NOT EXISTS `service_booking_calendars` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `calendar_title` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_countries`;
CREATE TABLE IF NOT EXISTS `service_booking_countries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country_title` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_dates`;
CREATE TABLE IF NOT EXISTS `service_booking_dates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `calendar_id` int(10) unsigned NOT NULL DEFAULT '0',
  `date` date NOT NULL DEFAULT '0000-00-00',
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `is_dayoff` enum('T','F') DEFAULT 'F',
  PRIMARY KEY (`id`),
  UNIQUE KEY `calendar_id` (`calendar_id`,`date`),
  KEY `is_dayoff` (`is_dayoff`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_employees`;
CREATE TABLE IF NOT EXISTS `service_booking_employees` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `calendar_id` int(10) unsigned DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `notes` text,
  `send_email` tinyint(1) unsigned DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `calendar_id` (`calendar_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_employees_services`;
CREATE TABLE IF NOT EXISTS `service_booking_employees_services` (
  `employee_id` int(10) unsigned NOT NULL,
  `service_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`employee_id`,`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_options`;
CREATE TABLE IF NOT EXISTS `service_booking_options` (
  `calendar_id` int(10) unsigned NOT NULL,
  `key` varchar(255) NOT NULL DEFAULT '',
  `tab_id` tinyint(3) unsigned DEFAULT NULL,
  `group` enum('borders','colors','fonts','sizes') DEFAULT NULL,
  `value` text,
  `description` text,
  `label` text,
  `type` enum('string','text','int','float','enum','color') NOT NULL DEFAULT 'string',
  `order` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`calendar_id`,`key`),
  KEY `tab_id` (`tab_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_roles`;
CREATE TABLE IF NOT EXISTS `service_booking_roles` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_services`;
CREATE TABLE IF NOT EXISTS `service_booking_services` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `calendar_id` int(10) unsigned DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `price` decimal(9,2) unsigned DEFAULT NULL,
  `length` smallint(5) unsigned DEFAULT NULL,
  `before` smallint(5) unsigned DEFAULT NULL,
  `after` smallint(5) unsigned DEFAULT NULL,
  `total` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `calendar_id` (`calendar_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_users`;
CREATE TABLE IF NOT EXISTS `service_booking_users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(10) unsigned NOT NULL,
  `username` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(40) NOT NULL DEFAULT '',
  `created` datetime NOT NULL,
  `last_login` datetime DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `role_id` (`role_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `service_booking_working_times`;
CREATE TABLE IF NOT EXISTS `service_booking_working_times` (
  `calendar_id` int(10) unsigned NOT NULL DEFAULT '0',
  `monday_from` time DEFAULT NULL,
  `monday_to` time DEFAULT NULL,
  `monday_dayoff` enum('T','F') DEFAULT 'F',
  `tuesday_from` time DEFAULT NULL,
  `tuesday_to` time DEFAULT NULL,
  `tuesday_dayoff` enum('T','F') DEFAULT 'F',
  `wednesday_from` time DEFAULT NULL,
  `wednesday_to` time DEFAULT NULL,
  `wednesday_dayoff` enum('T','F') DEFAULT 'F',
  `thursday_from` time DEFAULT NULL,
  `thursday_to` time DEFAULT NULL,
  `thursday_dayoff` enum('T','F') DEFAULT 'F',
  `friday_from` time DEFAULT NULL,
  `friday_to` time DEFAULT NULL,
  `friday_dayoff` enum('T','F') DEFAULT 'F',
  `saturday_from` time DEFAULT NULL,
  `saturday_to` time DEFAULT NULL,
  `saturday_dayoff` enum('T','F') DEFAULT 'F',
  `sunday_from` time DEFAULT NULL,
  `sunday_to` time DEFAULT NULL,
  `sunday_dayoff` enum('T','F') DEFAULT 'F',
  PRIMARY KEY (`calendar_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `service_booking_calendars` (`id`, `user_id`, `calendar_title`) VALUES
(1, NULL, 'Calendar 1');

INSERT INTO `service_booking_options` (`calendar_id`, `key`, `tab_id`, `group`, `value`, `description`, `label`, `type`, `order`) VALUES
(1, 'bf_include_address', 5, NULL, '1|2|3::2', 'Address<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 9),
(1, 'bf_include_captcha', 5, NULL, '1|2|3::3', 'Captcha<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 10),
(1, 'bf_include_city', 5, NULL, '1|2|3::2', 'City<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 6),
(1, 'bf_include_country', 5, NULL, '1|2|3::3', 'Country<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 5),
(1, 'bf_include_email', 5, NULL, '1|2|3::3', 'E-Mail address<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 2),
(1, 'bf_include_name', 5, NULL, '1|2|3::3', 'Name<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 1),
(1, 'bf_include_notes', 5, NULL, '1|2|3::2', 'Notes<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 4),
(1, 'bf_include_phone', 5, NULL, '1|2|3::2', 'Phone<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 3),
(1, 'bf_include_state', 5, NULL, '1|2|3::2', 'State<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 7),
(1, 'bf_include_zip', 5, NULL, '1|2|3::2', 'Zip<br />\r\n<span style="font-size: 0.9em">Select "Yes" if you want to include the field in the booking form, otherwise select "No"</span>', 'No|Yes|Yes (Required)', 'enum', 8),
(1, 'booking_status', 3, NULL, 'confirmed|pending|cancelled::pending', 'Default booking status<br />\r\n<span style="font-size: 0.9em">set the default status for each booking after it is made</span>', NULL, 'enum', 5),
(1, 'calendar_width', 2, NULL, '700', 'Calendar width (px)', NULL, 'int', 1),
(1, 'currency', 3, NULL, 'AUD|BRL|CAD|CZK|DKK|EUR|HKD|HUF|ILS|JPY|MYR|MXN|NOK|NZD|PHP|PLN|GBP|SGD|SEK|CHF|TWD|THB|USD::USD', 'Currency', NULL, 'enum', 1),
(1, 'datetime_format', 1, NULL, 'd.m.Y, H:i|d.m.Y, H:i:s|m.d.Y, H:i|m.d.Y, H:i:s|Y.m.d, H:i|Y.m.d, H:i:s|j.n.Y, H:i|j.n.Y, H:i:s|n.j.Y, H:i|n.j.Y, H:i:s|Y.n.j, H:i|Y.n.j, H:i:s|d/m/Y, H:i|d/m/Y, H:i:s|m/d/Y, H:i|m/d/Y, H:i:s|Y/m/d, H:i|Y/m/d, H:i:s|j/n/Y, H:i|j/n/Y, H:i:s|n/j/Y, H:i|n/j/Y, H:i:s|Y/n/j, H:i|Y/n/j, H:i:s|d-m-Y, H:i|d-m-Y, H:i:s|m-d-Y, H:i|m-d-Y, H:i:s|Y-m-d, H:i|Y-m-d, H:i:s|j-n-Y, H:i|j-n-Y, H:i:s|n-j-Y, H:i|n-j-Y, H:i:s|Y-n-j, H:i|Y-n-j, H:i:s::j/n/Y, H:i', 'Date/Time format', 'd.m.Y, H:i (25.09.2010, 09:51)|d.m.Y, H:i:s (25.09.2010, 09:51:47)|m.d.Y, H:i (09.25.2010, 09:51)|m.d.Y, H:i:s (09.25.2010, 09:51:47)|Y.m.d, H:i (2010.09.25, 09:51)|Y.m.d, H:i:s (2010.09.25, 09:51:47)|j.n.Y, H:i (25.9.2010, 09:51)|j.n.Y, H:i:s (25.9.2010, 09:51:47)|n.j.Y, H:i (9.25.2010, 09:51)|n.j.Y, H:i:s (9.25.2010, 09:51:47)|Y.n.j, H:i (2010.9.25, 09:51)|Y.n.j, H:i:s (2010.9.25, 09:51:47)|d/m/Y, H:i (25/09/2010, 09:51)|d/m/Y, H:i:s (25/09/2010, 09:51:47)|m/d/Y, H:i (09/25/2010, 09:51)|m/d/Y, H:i:s (09/25/2010, 09:51:47)|Y/m/d, H:i (2010/09/25, 09:51)|Y/m/d, H:i:s (2010/09/25, 09:51:47)|j/n/Y, H:i (25/9/2010, 09:51)|j/n/Y, H:i:s (25/9/2010, 09:51:47)|n/j/Y, H:i (9/25/2010, 09:51)|n/j/Y, H:i:s (9/25/2010, 09:51:47)|Y/n/j, H:i (2010/9/25, 09:51)|Y/n/j, H:i:s (2010/9/25, 09:51:47)|d-m-Y, H:i (25-09-2010, 09:51)|d-m-Y, H:i:s (25-09-2010, 09:51:47)|m-d-Y, H:i (09-25-2010, 09:51)|m-d-Y, H:i:s (09-25-2010, 09:51:47)|Y-m-d, H:i (2010-09-25, 09:51)|Y-m-d, H:i:s (2010-09-25, 09:51:47)|j-n-Y, H:i (25-9-2010, 09:51)|j-n-Y, H:i:s (25-9-2010, 09:51:47)|n-j-Y, H:i (9-25-2010, 09:51)|n-j-Y, H:i:s (9-25-2010, 09:51:47)|Y-n-j, H:i (2010-9-25, 09:51)|Y-n-j, H:i:s (2010-9-25, 09:51:47)', 'enum', 6),
(1, 'date_format', 1, NULL, 'd.m.Y|m.d.Y|Y.m.d|j.n.Y|n.j.Y|Y.n.j|d/m/Y|m/d/Y|Y/m/d|j/n/Y|n/j/Y|Y/n/j|d-m-Y|m-d-Y|Y-m-d|j-n-Y|n-j-Y|Y-n-j::j/n/Y', 'Date format', 'd.m.Y (25.09.2010)|m.d.Y (09.25.2010)|Y.m.d (2010.09.25)|j.n.Y (25.9.2010)|n.j.Y (9.25.2010)|Y.n.j (2010.9.25)|d/m/Y (25/09/2010)|m/d/Y (09/25/2010)|Y/m/d (2010/09/25)|j/n/Y (25/9/2010)|n/j/Y (9/25/2010)|Y/n/j (2010/9/25)|d-m-Y (25-09-2010)|m-d-Y (09-25-2010)|Y-m-d (2010-09-25)|j-n-Y (25-9-2010)|n-j-Y (9-25-2010)|Y-n-j (2010-9-25)', 'enum', 8),
(1, 'deposit_percent', 3, NULL, '25', 'Deposit payment %<br />\r\n<span style="font-size: 0.9em">set % of the booking amount to be paid as a deposit. For full payment enter 100</span>', NULL, 'int', 2),
(1, 'email_address', 4, NULL, 'info@domain.com', 'Notification email address', NULL, 'string', 1),
(1, 'email_confirmation', 4, NULL, '1|2|3::3', 'Send confirmation email<br />\r\n<span style="font-size: 0.9em">select if and when confirmation email should be sent to clients after they make a booking</span>', 'None|After booking form|After payment', 'enum', 2),
(1, 'email_confirmation_message', 4, NULL, 'You''ve just made a booking.\r\n\r\nPersonal details:\r\nName: {Name}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nNotes: {Notes}\r\n\r\nBooking details:\r\nBooking ID: {BookingID}\r\nServices: {Services}\r\nDeposit: {Deposit}\r\nTotal: {Total}\r\nTax: {Tax}\r\n\r\nIf you want to cancel your booking follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.', 'Confirmation email<br />\r\n<u>Available Tokens:</u><br />\r\n{Name}<br />\r\n{Email}<br />\r\n{Phone}<br />\r\n{Country}<br />\r\n{City}<br />\r\n{State}<br />\r\n{Zip}<br />\r\n{Address}<br />\r\n{Notes}<br />\r\n{BookingID}<br />\r\n{Services}<br />\r\n{Deposit}<br />\r\n{Total}<br />\r\n{Tax}<br />\r\n{PaymentMethod}<br />\r\n{PaymentOption}<br />\r\n{CCType}<br />\r\n{CCNum}<br />\r\n{CCExp}<br />\r\n{CCSec}<br />\r\n{CancelURL}<br />', NULL, 'text', 4),
(1, 'email_confirmation_subject', 4, NULL, 'Confirmation message', 'Confirmation email subject', NULL, 'string', 3),
(1, 'email_payment', 4, NULL, '1|3::1', 'Send payment confirmation email<br />\r\n<span style="font-size: 0.9em">select if and when confirmation email should be sent to clients after they make a payment for their booking</span>', 'None|After payment', 'enum', 5),
(1, 'email_payment_message', 4, NULL, 'You''ve just made a booking.\r\n\r\nPersonal details:\r\nName: {Name}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nCountry: {Country}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nNotes: {Notes}\r\n\r\nBooking details:\r\nBooking ID: {BookingID}\r\nServices: {Services}\r\nDeposit: {Deposit}\r\nTotal: {Total}\r\nTax: {Tax}\r\n\r\nIf you want to cancel your booking follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.', 'Payment email<br />\r\n<u>Available Tokens:</u><br />\r\n{Name}<br />\r\n{Email}<br />\r\n{Phone}<br />\r\n{Country}<br />\r\n{City}<br />\r\n{State}<br />\r\n{Zip}<br />\r\n{Address}<br />\r\n{Notes}<br />\r\n{BookingID}<br />\r\n{Services}<br />\r\n{Deposit}<br />\r\n{Total}<br />\r\n{Tax}<br />\r\n{PaymentMethod}<br />\r\n{PaymentOption}<br />\r\n{CCType}<br />\r\n{CCNum}<br />\r\n{CCExp}<br />\r\n{CCSec}<br />\r\n{CancelURL}<br />', NULL, 'text', 7),
(1, 'email_payment_subject', 4, NULL, 'Payment message', 'Payment email subject', NULL, 'string', 6),
(1, 'font_family', 2, 'fonts', 'Arial|Arial Black|Book Antiqua|Century|Century Gothic|Comic Sans MS|Courier|Courier New|Impact|Lucida Console|Lucida Sans Unicode|Monotype Corsiva|Modern|Sans Serif|Serif|Small fonts|Symbol|Tahoma|Times New Roman|Verdana::Arial', 'Font family<br />\r\n<span style="font-size: 0.9em">default font family for all the text</span>', 'Arial|Arial Black|Book Antiqua|Century|Century Gothic|Comic Sans MS|Courier|Courier New|Impact|Lucida Console|Lucida Sans Unicode|Monotype Corsiva|Modern|Sans Serif|Serif|Small fonts|Symbol|Tahoma|Times New Roman|Verdana', 'enum', 300),
(1, 'font_size', 2, 'sizes', '10|12|14|16|18|20|22|24|26|28|30::12', 'Font size', NULL, 'enum', 406),
(1, 'font_weight', 2, 'fonts', 'font-weight: normal|font-weight: bold|font-style: italic|text-decoration: underline|font-weight: bold; font-style: italic::font-style: italic', 'Font style', 'Normal|Bold|Italic|Underline|Bold Italic', 'enum', 301),
(1, 'hide_prices', 3, NULL, 'Yes|No::No', 'Hide prices', NULL, 'enum', 29),
(1, 'payment_authorize_key', 3, NULL, '', 'Authorize.net transaction key', NULL, 'string', 34),
(1, 'payment_authorize_mid', 3, NULL, '', 'Authorize.net merchant ID', NULL, 'string', 35),
(1, 'payment_disable', 3, NULL, 'No|Yes::No', 'Disable payments<br /><span style="font-size: 0.9em">to disable payments and only accept bookings, set this to "Yes"</span>', NULL, 'enum', 30),
(1, 'payment_enable_authorize', 3, NULL, 'Yes|No::No', 'Allow Authorize.net payments', NULL, 'enum', 33),
(1, 'payment_enable_creditcard', 3, NULL, 'Yes|No::Yes', 'Allow payments with Credit cards', NULL, 'enum', 38),
(1, 'payment_enable_paypal', 3, NULL, 'Yes|No::Yes', 'Allow PayPal payments', NULL, 'enum', 31),
(1, 'payment_status', 3, NULL, 'confirmed|pending|cancelled::confirmed', 'Default booking status after payment<br />\r\n<span style="font-size: 0.9em">set the default status for each booking after payment is made for it</span>', NULL, 'enum', 6),
(1, 'paypal_address', 3, NULL, 'paypal@domain.com', 'PayPal business email address', NULL, 'string', 32),
(1, 'reminder_body', 6, NULL, 'You''ve just made a booking.\r\n\r\nPersonal details:\r\nName: {Name}\r\nE-Mail: {Email}\r\nPhone: {Phone}\r\nCountry: {Country}\r\nCity: {City}\r\nState: {State}\r\nZip: {Zip}\r\nAddress: {Address}\r\nNotes: {Notes}\r\n\r\nBooking details:\r\nBooking ID: {BookingID}\r\nServices: {Services}\r\nDeposit: {Deposit}\r\nTotal: {Total}\r\nTax: {Tax}\r\n\r\nIf you want to cancel your booking follow next link: {CancelURL}\r\n\r\nThank you, we will contact you ASAP.', 'Email Reminder body<br />\r\n<u>Available Tokens:</u><br />\r\n{Name}<br />\r\n{Email}<br />\r\n{Phone}<br />\r\n{Country}<br />\r\n{City}<br />\r\n{State}<br />\r\n{Zip}<br />\r\n{Address}<br />\r\n{Notes}<br />\r\n{BookingID}<br />\r\n{Services}<br />\r\n{Deposit}<br />\r\n{Total}<br />\r\n{Tax}<br />\r\n{PaymentMethod}<br />\r\n{PaymentOption}<br />\r\n{CCType}<br />\r\n{CCNum}<br />\r\n{CCExp}<br />\r\n{CCSec}<br />\r\n{CancelURL}<br />', NULL, 'text', 4),
(1, 'reminder_email_before', 6, NULL, '2', 'Send email reminder', NULL, 'int', 2),
(1, 'reminder_enable', 6, NULL, 'Yes|No::Yes', 'Enable notifications', NULL, 'enum', 1),
(1, 'reminder_sms_api', 6, NULL, '', 'SMS api key', NULL, 'string', 6),
(1, 'reminder_sms_hours', 6, NULL, '1', 'Send SMS reminder', NULL, 'int', 5),
(1, 'reminder_sms_message', 6, NULL, '{Name}, booking reminder\r\n\r\n{Services}', 'SMS message<br />\r\n<u>Available Tokens:</u><br />\r\n{Name}<br />\r\n{Email}<br />\r\n{Phone}<br />\r\n{Country}<br />\r\n{City}<br />\r\n{State}<br />\r\n{Zip}<br />\r\n{Address}<br />\r\n{Notes}<br />\r\n{BookingID}<br />\r\n{Services}<br />\r\n{Deposit}<br />\r\n{Total}<br />\r\n{Tax}<br />\r\n{PaymentMethod}<br />\r\n{PaymentOption}<br />\r\n{CCType}<br />\r\n{CCNum}<br />\r\n{CCExp}<br />\r\n{CCSec}<br />\r\n{CancelURL}<br />', NULL, 'text', 7),
(1, 'reminder_subject', 6, NULL, 'Booking Reminder', 'Email Reminder subject', NULL, 'string', 3),
(1, 'step', 3, NULL, '5|10|15|20|25|30|35|40|45|50|55|60::15', 'Step (in minutes)', NULL, 'enum', 10),
(1, 'tax', 3, NULL, '10', 'Tax payment %<br />\r\n<span style="font-size: 0.9em">set % for tax that clients pay</span>', NULL, 'float', 3),
(1, 'thank_you_page', 3, NULL, 'http://www.domain.com', '"Thank you" page location<br />\r\n<span style="font-size: 0.9em">this is the page where people will be redirected after paying</span>', NULL, 'string', 7),
(1, 'timezone', 1, NULL, '-43200|-39600|-36000|-32400|-28800|-25200|-21600|-18000|-14400|-10800|-7200|-3600|0|3600|7200|10800|14400|18000|21600|25200|28800|32400|36000|39600|43200|46800::0', 'Timezone<br />\r\n<span style="font-size: 0.9em">select your time zone so booking interval can be limited based on your time zone</span>', 'GMT-12:00|GMT-11:00|GMT-10:00|GMT-09:00|GMT-08:00|GMT-07:00|GMT-06:00|GMT-05:00|GMT-04:00|GMT-03:00|GMT-02:00|GMT-01:00|GMT|GMT+01:00|GMT+02:00|GMT+03:00|GMT+04:00|GMT+05:00|GMT+06:00|GMT+07:00|GMT+08:00|GMT+09:00|GMT+10:00|GMT+11:00|GMT+12:00|GMT+13:00', 'enum', 12),
(1, 'time_format', 1, NULL, 'H:i|G:i|h:i|h:i a|h:i A|g:i|g:i a|g:i A::H:i', 'Time format', 'H:i (09:45)|G:i (9:45)|h:i (09:45)|h:i a (09:45 am)|h:i A (09:45 AM)|g:i (9:45)|g:i a (9:45 am)|g:i A (9:45 AM)', 'enum', 9),
(1, 'admin_phone', 1, NULL, NULL, 'Admin phone', NULL, 'string', 5);

INSERT INTO `service_booking_roles` (`id`, `role`, `status`) VALUES
(1, 'admin', 'T'),
(2, 'owner', 'T');

INSERT INTO `service_booking_countries` (`id`, `country_title`, `status`) VALUES
(NULL, 'Afghanistan', default),
(NULL, 'Albania', default),
(NULL, 'Algeria', default),
(NULL, 'American Samoa', default),
(NULL, 'Andorra', default),
(NULL, 'Angola', default),
(NULL, 'Anguilla', default),
(NULL, 'Antarctica', default),
(NULL, 'Antigua and Barbuda', default),
(NULL, 'Argentina', default),
(NULL, 'Armenia', default),
(NULL, 'Arctic Ocean', default),
(NULL, 'Aruba', default),
(NULL, 'Ashmore and Cartier Islands', default),
(NULL, 'Atlantic Ocean', default),
(NULL, 'Australia', default),
(NULL, 'Austria', default),
(NULL, 'Azerbaijan', default),
(NULL, 'Bahamas', default),
(NULL, 'Bahrain', default),
(NULL, 'Baker Island', default),
(NULL, 'Bangladesh', default),
(NULL, 'Barbados', default),
(NULL, 'Bassas da India', default),
(NULL, 'Belarus', default),
(NULL, 'Belgium', default),
(NULL, 'Belize', default),
(NULL, 'Benin', default),
(NULL, 'Bermuda', default),
(NULL, 'Bhutan', default),
(NULL, 'Bolivia', default),
(NULL, 'Borneo', default),
(NULL, 'Bosnia and Herzegovina', default),
(NULL, 'Botswana', default),
(NULL, 'Bouvet Island', default),
(NULL, 'Brazil', default),
(NULL, 'British Virgin Islands', default),
(NULL, 'Brunei', default),
(NULL, 'Bulgaria', default),
(NULL, 'Burkina Faso', default),
(NULL, 'Burundi', default),
(NULL, 'Cambodia', default),
(NULL, 'Cameroon', default),
(NULL, 'Canada', default),
(NULL, 'Cape Verde', default),
(NULL, 'Cayman Islands', default),
(NULL, 'Central African Republic', default),
(NULL, 'Chad', default),
(NULL, 'Chile', default),
(NULL, 'China', default),
(NULL, 'Christmas Island', default),
(NULL, 'Clipperton Island', default),
(NULL, 'Cocos Islands', default),
(NULL, 'Colombia', default),
(NULL, 'Comoros', default),
(NULL, 'Cook Islands', default),
(NULL, 'Coral Sea Islands', default),
(NULL, 'Costa Rica', default),
(NULL, 'Cote d\'Ivoire', default),
(NULL, 'Croatia', default),
(NULL, 'Cuba', default),
(NULL, 'Cyprus', default),
(NULL, 'Czech Republic', default),
(NULL, 'Denmark', default),
(NULL, 'Democratic Republic of the Congo', default),
(NULL, 'Djibouti', default),
(NULL, 'Dominica', default),
(NULL, 'Dominican Republic', default),
(NULL, 'East Timor', default),
(NULL, 'Ecuador', default),
(NULL, 'Egypt', default),
(NULL, 'El Salvador', default),
(NULL, 'Equatorial Guinea', default),
(NULL, 'Eritrea', default),
(NULL, 'Estonia', default),
(NULL, 'Ethiopia', default),
(NULL, 'Europa Island', default),
(NULL, 'Falkland Islands (Islas Malvinas)', default),
(NULL, 'Faroe Islands', default),
(NULL, 'Fiji', default),
(NULL, 'Finland', default),
(NULL, 'France', default),
(NULL, 'French Guiana', default),
(NULL, 'French Polynesia', default),
(NULL, 'French Southern and Antarctic Lands', default),
(NULL, 'Gabon', default),
(NULL, 'Gambia', default),
(NULL, 'Gaza Strip', default),
(NULL, 'Georgia', default),
(NULL, 'Germany', default),
(NULL, 'Ghana', default),
(NULL, 'Gibraltar', default),
(NULL, 'Glorioso Islands', default),
(NULL, 'Greece', default),
(NULL, 'Greenland', default),
(NULL, 'Grenada', default),
(NULL, 'Guadeloupe', default),
(NULL, 'Guam', default),
(NULL, 'Guatemala', default),
(NULL, 'Guernsey', default),
(NULL, 'Guinea', default),
(NULL, 'Guinea-Bissau', default),
(NULL, 'Guyana', default),
(NULL, 'Haiti', default),
(NULL, 'Heard Island and McDonald Islands', default),
(NULL, 'Honduras', default),
(NULL, 'Hong Kong', default),
(NULL, 'Howland Island', default),
(NULL, 'Hungary', default),
(NULL, 'Iceland', default),
(NULL, 'India', default),
(NULL, 'Indian Ocean', default),
(NULL, 'Indonesia', default),
(NULL, 'Iran', default),
(NULL, 'Iraq', default),
(NULL, 'Ireland', default),
(NULL, 'Isle of Man', default),
(NULL, 'Israel', default),
(NULL, 'Italy', default),
(NULL, 'Jamaica', default),
(NULL, 'Jan Mayen', default),
(NULL, 'Japan', default),
(NULL, 'Jarvis Island', default),
(NULL, 'Jersey', default),
(NULL, 'Johnston Atoll', default),
(NULL, 'Jordan', default),
(NULL, 'Juan de Nova Island', default),
(NULL, 'Kazakhstan', default),
(NULL, 'Kenya', default),
(NULL, 'Kingman Reef', default),
(NULL, 'Kiribati', default),
(NULL, 'Kerguelen Archipelago', default),
(NULL, 'Kosovo', default),
(NULL, 'Kuwait', default),
(NULL, 'Kyrgyzstan', default),
(NULL, 'Laos', default),
(NULL, 'Latvia', default),
(NULL, 'Lebanon', default),
(NULL, 'Lesotho', default),
(NULL, 'Liberia', default),
(NULL, 'Libya', default),
(NULL, 'Liechtenstein', default),
(NULL, 'Lithuania', default),
(NULL, 'Luxembourg', default),
(NULL, 'Macau', default),
(NULL, 'Macedonia', default),
(NULL, 'Madagascar', default),
(NULL, 'Malawi', default),
(NULL, 'Malaysia', default),
(NULL, 'Maldives', default),
(NULL, 'Mali', default),
(NULL, 'Malta', default),
(NULL, 'Marshall Islands', default),
(NULL, 'Martinique', default),
(NULL, 'Mauritania', default),
(NULL, 'Mauritius', default),
(NULL, 'Mayotte', default),
(NULL, 'Mediterranean Sea', default),
(NULL, 'Mexico', default),
(NULL, 'Micronesia', default),
(NULL, 'Midway Islands', default),
(NULL, 'Moldova', default),
(NULL, 'Monaco', default),
(NULL, 'Mongolia', default),
(NULL, 'Montenegro', default),
(NULL, 'Montserrat', default),
(NULL, 'Morocco', default),
(NULL, 'Mozambique', default),
(NULL, 'Myanmar', default),
(NULL, 'Namibia', default),
(NULL, 'Nauru', default),
(NULL, 'Navassa Island', default),
(NULL, 'Nepal', default),
(NULL, 'Netherlands', default),
(NULL, 'Netherlands Antilles', default),
(NULL, 'New Caledonia', default),
(NULL, 'New Zealand', default),
(NULL, 'Nicaragua', default),
(NULL, 'Niger', default),
(NULL, 'Nigeria', default),
(NULL, 'Niue', default),
(NULL, 'Norfolk Island', default),
(NULL, 'North Korea', default),
(NULL, 'North Sea', default),
(NULL, 'Northern Mariana Islands', default),
(NULL, 'Norway', default),
(NULL, 'Oman', default),
(NULL, 'Pacific Ocean', default),
(NULL, 'Pakistan', default),
(NULL, 'Palau', default),
(NULL, 'Palmyra Atoll', default),
(NULL, 'Panama', default),
(NULL, 'Papua New Guinea', default),
(NULL, 'Paracel Islands', default),
(NULL, 'Paraguay', default),
(NULL, 'Peru', default),
(NULL, 'Philippines', default),
(NULL, 'Pitcairn Islands', default),
(NULL, 'Poland', default),
(NULL, 'Portugal', default),
(NULL, 'Puerto Rico', default),
(NULL, 'Qatar', default),
(NULL, 'Reunion', default),
(NULL, 'Republic of the Congo', default),
(NULL, 'Romania', default),
(NULL, 'Ross Sea', default),
(NULL, 'Russia', default),
(NULL, 'Rwanda', default),
(NULL, 'Saint Helena', default),
(NULL, 'Saint Kitts and Nevis', default),
(NULL, 'Saint Lucia', default),
(NULL, 'Saint Pierre and Miquelon', default),
(NULL, 'Saint Vincent and the Grenadines', default),
(NULL, 'Samoa', default),
(NULL, 'San Marino', default),
(NULL, 'Sao Tome and Principe', default),
(NULL, 'Saudi Arabia', default),
(NULL, 'Senegal', default),
(NULL, 'Serbia', default),
(NULL, 'Seychelles', default),
(NULL, 'Sierra Leone', default),
(NULL, 'Singapore', default),
(NULL, 'Slovakia', default),
(NULL, 'Slovenia', default),
(NULL, 'Solomon Islands', default),
(NULL, 'Somalia', default),
(NULL, 'South Africa', default),
(NULL, 'South Georgia and the South Sandwich Islands', default),
(NULL, 'South Korea', default),
(NULL, 'Southern Ocean', default),
(NULL, 'Spain', default),
(NULL, 'Spratly Islands', default),
(NULL, 'Sri Lanka', default),
(NULL, 'Sudan', default),
(NULL, 'Suriname', default),
(NULL, 'Svalbard', default),
(NULL, 'Swaziland', default),
(NULL, 'Sweden', default),
(NULL, 'Switzerland', default),
(NULL, 'Syria', default),
(NULL, 'Taiwan', default),
(NULL, 'Tajikistan', default),
(NULL, 'Tanzania', default),
(NULL, 'Tasman Sea', default),
(NULL, 'Thailand', default),
(NULL, 'Togo', default),
(NULL, 'Tokelau', default),
(NULL, 'Tonga', default),
(NULL, 'Trinidad and Tobago', default),
(NULL, 'Tromelin Island', default),
(NULL, 'Tunisia', default),
(NULL, 'Turkey', default),
(NULL, 'Turkmenistan', default),
(NULL, 'Turks and Caicos Islands', default),
(NULL, 'Tuvalu', default),
(NULL, 'Uganda', default),
(NULL, 'Ukraine', default),
(NULL, 'United Arab Emirates', default),
(NULL, 'United Kingdom', default),
(NULL, 'USA', default),
(NULL, 'Uruguay', default),
(NULL, 'Uzbekistan', default),
(NULL, 'Vanuatu', default),
(NULL, 'Venezuela', default),
(NULL, 'Viet Nam', default),
(NULL, 'Virgin Islands', default),
(NULL, 'Wake Island', default),
(NULL, 'Wallis and Futuna', default),
(NULL, 'West Bank', default),
(NULL, 'Western Sahara', default),
(NULL, 'Yemen', default),
(NULL, 'Zambia', default),
(NULL, 'Zimbabwe', default);

INSERT INTO `service_booking_working_times` (`calendar_id`, `monday_from`, `monday_to`, `monday_dayoff`, `tuesday_from`, `tuesday_to`, `tuesday_dayoff`, `wednesday_from`, `wednesday_to`, `wednesday_dayoff`, `thursday_from`, `thursday_to`, `thursday_dayoff`, `friday_from`, `friday_to`, `friday_dayoff`, `saturday_from`, `saturday_to`, `saturday_dayoff`, `sunday_from`, `sunday_to`, `sunday_dayoff`) VALUES
(1, '09:00:00', '18:00:00', 'F', '09:00:00', '18:00:00', 'F', '09:00:00', '18:00:00', 'F', '08:00:00', '18:00:00', 'F', '09:00:00', '18:00:00', 'F', NULL, NULL, 'T', NULL, NULL, 'T');